#!/bin/bash

name_list=(Aug23 Aug27 Sep02 Sep04 Sep06 Sep09 Sep11 Sep13 Sep17 Sep19 Sep30 Oct02 Oct04 Oct08 Oct10 Oct15 Oct23 Oct25 Oct28 Oct29 Oct30 Oct31 Nov17 Nov18 Nov29 Nov30)
month_list=(8 8 9 9 9 9 9 9 9 9 9 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11)
day_list=(23 27 2 4 6 9 11 13 17 19 30 2 4 8 10 15 23 25 28 29 30 31 17 18 29 30)

for i in {0..25}
do
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 8 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_plusfour.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
      echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 6 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_plusthree.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
     echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 4 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_plustwo.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 2 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_plusone.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 0 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_zenith.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 1 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_minusone.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 3 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_minustwo.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt 
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 5 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_minusthree.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt   
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 7 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_minusfour.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
   echo "\COPY (select observation_info.obsid from observation_info where observation_info.date[1]=2013 AND observation_info.date[2] = ${month_list[$i]} AND observation_info.date[3]= ${day_list[$i]} AND observation_info.gridnum = 9 ORDER BY obsid ASC) TO '/nfs/eor-00/h1/nbarry/MWA/IDL_code/obs_list/longrun_queries/uncut/${name_list[$i]}_minusfive.txt'" >> ~/MWA/IDL_code/obs_list/longrun_queries/uncut/copy_commands_cut.txt
done

